spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: cauldron
    password:
    hikari:
      jdbc-url: jdbc:h2:file:./target/h2db/db/cauldrondb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2-console